const $=s=>document.querySelector(s),publicMoney=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});
let cityResults=[],chosenCity=null,eiaData=null,cityTimer;
const cityLabel=p=>[p.name,p.admin1,p.country].filter(Boolean).join(", ");
function lineChart(target,series,colors){
 const all=series.flatMap(s=>s.values),min=Math.min(...all),max=Math.max(...all),x=i=>5+i/(series[0].values.length-1)*90,y=v=>90-(v-min)/(max-min||1)*75;
 const lines=series.map((s,j)=>`<polyline points="${s.values.map((v,i)=>`${x(i)},${y(v)}`).join(" ")}" fill="none" stroke="${colors[j]}" stroke-width="2"/><g fill="${colors[j]}">${s.values.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="1.8"><title>${s.label}: ${v.toFixed(1)}</title></circle>`).join("")}</g>`).join("");
 target.classList.remove("empty-chart");target.innerHTML=`<svg viewBox="0 0 100 100" preserveAspectRatio="none">${lines}</svg><div class="chart-legend">${series.map((s,i)=>`<span><i style="background:${colors[i]}"></i>${s.label}</span>`).join("")}</div>`;
}
function barChart(target,values,labels){const max=Math.max(...values);target.classList.remove("empty-chart");target.innerHTML=values.map((v,i)=>`<div><i style="height:${v/max*100}%"><b>${v.toFixed(1)}</b></i><span>${labels[i]}</span></div>`).join("")}
function pearson(rows){if(rows.length<3)return null;const mx=rows.reduce((s,r)=>s+r.x,0)/rows.length,my=rows.reduce((s,r)=>s+r.y,0)/rows.length,num=rows.reduce((s,r)=>s+(r.x-mx)*(r.y-my),0),den=Math.sqrt(rows.reduce((s,r)=>s+(r.x-mx)**2,0)*rows.reduce((s,r)=>s+(r.y-my)**2,0));return den?num/den:null}
function strength(r){const n=Math.abs(r);return n<.2?"very weak":n<.4?"weak":n<.6?"moderate":n<.8?"strong":"very strong"}
function showCityResults(){const menu=$("#public-suggestions");menu.innerHTML=cityResults.map((p,i)=>`<button type="button" data-index="${i}"><b>${p.name}</b><span>${[p.admin1,p.country].filter(Boolean).join(", ")}</span></button>`).join("");menu.hidden=!cityResults.length}
async function findCities(term){if(term.trim().length<2){cityResults=[];showCityResults();return}const result=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(term)}&count=8&language=en&format=json`).then(r=>r.json());cityResults=result.results||[];showCityResults()}
$("#public-city").addEventListener("input",e=>{clearTimeout(cityTimer);cityTimer=setTimeout(()=>findCities(e.target.value).catch(()=>{}),220)});
$("#public-city").addEventListener("keydown",e=>{const buttons=[...$("#public-suggestions").querySelectorAll("button")];if(!buttons.length)return;let active=buttons.findIndex(b=>b.classList.contains("active"));if(e.key==="ArrowDown"){e.preventDefault();active=(active+1)%buttons.length}else if(e.key==="ArrowUp"){e.preventDefault();active=(active-1+buttons.length)%buttons.length}else if(e.key==="Enter"&&active>=0){e.preventDefault();buttons[active].click();return}else if(e.key==="Escape"){$("#public-suggestions").hidden=true;return}else{return}buttons.forEach((b,i)=>b.classList.toggle("active",i===active));buttons[active].scrollIntoView({block:"nearest"})});
$("#public-suggestions").addEventListener("mousedown",e=>{const button=e.target.closest("button");if(!button)return;e.preventDefault();chosenCity=cityResults[Number(button.dataset.index)];$("#public-city").value=cityLabel(chosenCity);$("#public-suggestions").hidden=true});
document.addEventListener("click",e=>{if(!e.target.closest(".city-picker"))$("#public-suggestions").hidden=true});
const codeText=c=>({0:"Clear skies",1:"Mainly clear",2:"Partly cloudy",3:"Overcast",45:"Fog",51:"Light drizzle",61:"Rain",71:"Snow",80:"Rain showers",95:"Thunderstorm"}[c]||"Current conditions");
async function annualCityWeather(history){
 const start=`${history[0].period}-01-01`,end=`${history.at(-1).period}-12-31`,url=`https://archive-api.open-meteo.com/v1/archive?latitude=${chosenCity.latitude}&longitude=${chosenCity.longitude}&start_date=${start}&end_date=${end}&daily=temperature_2m_mean&temperature_unit=fahrenheit&timezone=auto`,weather=await fetch(url).then(r=>r.json()),groups={};
 weather.daily.time.forEach((d,i)=>{const year=d.slice(0,4),v=weather.daily.temperature_2m_mean[i];if(Number.isFinite(v))(groups[year]??=[]).push(v)});return Object.fromEntries(Object.entries(groups).map(([year,v])=>[year,v.reduce((a,b)=>a+b,0)/v.length]));
}
async function loadCity(){
 const error=$("#public-error"),button=$("#public-city-form button");error.hidden=true;button.disabled=true;button.textContent="Loading data…";
 try{
  if(!chosenCity||cityLabel(chosenCity)!==$("#public-city").value){await findCities($("#public-city").value);chosenCity=cityResults[0]}if(!chosenCity)throw Error("Choose a city from the suggestion menu.");
  const url=`https://api.open-meteo.com/v1/forecast?latitude=${chosenCity.latitude}&longitude=${chosenCity.longitude}&current=temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,shortwave_radiation_sum&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=auto`,weather=await fetch(url).then(r=>r.json()),name=cityLabel(chosenCity),days=weather.daily.time.map(x=>new Date(x+"T12:00:00").toLocaleDateString(undefined,{weekday:"short"})),solar=weather.daily.shortwave_radiation_sum.map(x=>x/3.6);
  $("#public-city").value=name;$("#public-place").textContent=name.toUpperCase();$("#public-temp").textContent=`${Math.round(weather.current.temperature_2m)}°`;$("#public-description").textContent=codeText(weather.current.weather_code);$("#public-feels").textContent=`${Math.round(weather.current.apparent_temperature)}°`;$("#public-humidity").textContent=`${weather.current.relative_humidity_2m}%`;$("#public-wind").textContent=`${weather.current.wind_speed_10m.toFixed(1)} mph`;$("#public-highlow").textContent=`${Math.round(weather.daily.temperature_2m_max[0])}° / ${Math.round(weather.daily.temperature_2m_min[0])}°`;$("#hero-city").textContent=chosenCity.name.toUpperCase();$("#hero-temp").textContent=`${Math.round(weather.current.temperature_2m)}°`;$("#hero-condition").textContent=codeText(weather.current.weather_code);$("#stat-high").textContent=`${Math.round(weather.daily.temperature_2m_max[0])}°`;$("#stat-low").textContent=`${Math.round(weather.daily.temperature_2m_min[0])}°`;$("#stat-solar").textContent=`${solar[0].toFixed(1)} kWh/m²`;$("#public-solar").textContent=`${solar[0].toFixed(1)} kWh/m²`;$("#chart-context").textContent=`Public weather and electricity patterns for ${name}.`;
  lineChart($("#temperature-chart"),[{label:"High",values:weather.daily.temperature_2m_max},{label:"Low",values:weather.daily.temperature_2m_min}],["#ff7657","#013e37"]);barChart($("#solar-chart"),solar,days);
  if(!eiaData)eiaData=await fetch(`data/eia-state-energy.json?v=${Date.now()}`).then(r=>r.json());const state=eiaData.states?.[chosenCity.admin1];if(!state)throw Error("Weather loaded, but EIA state data is only available for U.S. locations.");
  $("#public-rate").textContent=`${state.residentialPriceCents.toFixed(2)}¢/kWh`;$("#public-usage").textContent=`${Math.round(state.averageMonthlyKwh).toLocaleString()} kWh/mo`;$("#public-rate-note").textContent=`${chosenCity.admin1} home average · EIA ${state.period}`;$("#public-usage-note").textContent=`Average monthly household use in ${chosenCity.admin1}`;$("#hero-state-usage").textContent=`${Math.round(state.averageMonthlyKwh).toLocaleString()} kWh/mo`;$("#stat-rate").textContent=`${state.residentialPriceCents.toFixed(2)}¢`;$("#mini-bars").innerHTML=state.history.slice(-10).map(x=>`<i style="height:${x.averageMonthlyKwh/Math.max(...state.history.map(y=>y.averageMonthlyKwh))*100}%"></i>`).join("");
  lineChart($("#rate-chart"),[{label:"Price ¢/kWh",values:state.history.map(x=>x.residentialPriceCents)}],["#ff7657"]);lineChart($("#state-usage-chart"),[{label:"kWh/month",values:state.history.map(x=>x.averageMonthlyKwh)}],["#013e37"]);
  const annual=await annualCityWeather(state.history),joined=state.history.filter(x=>Number.isFinite(annual[x.period])).map(x=>({x:annual[x.period],y:x.averageMonthlyKwh})),r=pearson(joined);$("#public-correlation").textContent=r===null?"—":r.toFixed(2);$("#public-correlation-note").textContent=r===null?"Not enough matched years":`${joined.length} years show a ${strength(r)} connection between ${chosenCity.name} temperature and ${chosenCity.admin1} home electricity use.`;
 }catch(ex){error.textContent=ex.message;error.hidden=false}finally{button.disabled=false;button.textContent="Load city dashboard →"}
}
$("#public-city-form").addEventListener("submit",e=>{e.preventDefault();loadCity()});
