const $=s=>document.querySelector(s),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});
let cityName="Denver",data=[],suggestions=new Map(),suggestionTimer;
function randomFactory(seed){return()=>((seed=Math.imul(1664525,seed)+1013904223|0)>>>0)/4294967296}
function temperatures(latitude=39.74){const random=randomFactory(20260727+Math.round(Math.abs(latitude)*100));return Array.from({length:730},(_,i)=>{const date=new Date();date.setDate(date.getDate()-(729-i));const doy=Math.floor((date-new Date(date.getFullYear(),0,0))/864e5),phase=latitude>=0?105:287,range=clamp(Math.abs(latitude)*.55,9,31),center=clamp(78-Math.abs(latitude)*.62,42,72);return{date,temp:center+range*Math.sin(2*Math.PI*(doy-phase)/365.25)+(random()-.5)*12}})}
function buildEnergy(temps,latitude=39.74){const random=randomFactory(20260727+Math.round(Math.abs(latitude)*100));return temps.map((d,i)=>{let usage=16+Math.max(0,65-d.temp)*.38+Math.max(0,d.temp-68)*.52+(d.date.getDay()%6===0?2.2:0)+(random()-.5)*4.2;if(i%97===0)usage+=16;usage=Math.max(4,usage);return{...d,usage,cost:usage*.145,rate:.145}})}
function percentile(a,p){return a[Math.floor((a.length-1)*p)]}
function render(){
 const usage=data.map(d=>d.usage),avg=usage.reduce((a,b)=>a+b,0)/usage.length,total=usage.reduce((a,b)=>a+b,0),sorted=[...usage].sort((a,b)=>a-b),median=(sorted[364]+sorted[365])/2,sd=Math.sqrt(usage.reduce((s,n)=>s+(n-avg)**2,0)/(usage.length-1)),meanT=data.reduce((s,d)=>s+d.temp,0)/data.length,cov=data.reduce((s,d)=>s+(d.temp-meanT)*(d.usage-avg),0),corr=cov/Math.sqrt(data.reduce((s,d)=>s+(d.temp-meanT)**2,0)*usage.reduce((s,n)=>s+(n-avg)**2,0)),high=percentile(sorted,.75)+1.5*(percentile(sorted,.75)-percentile(sorted,.25)),anomalies=usage.filter(n=>n>high).length;
 $("#hero-average").textContent=`${avg.toFixed(1)} kWh`;$("#stat-days").textContent=data.length.toLocaleString();$("#stat-kwh").textContent=Math.round(total).toLocaleString();$("#stat-correlation").textContent=corr.toFixed(2);$("#stat-anomalies").textContent=anomalies;$("#mini-bars").innerHTML=data.slice(-18).map(d=>`<i style="height:${clamp(d.usage/55*100,10,100)}%"></i>`).join("");
 const kpis=[["Total usage",Math.round(total).toLocaleString(),"kWh"],["Daily average",avg.toFixed(1),"kWh / day"],["Total cost",money.format(data.reduce((s,d)=>s+d.cost,0)),"observed period"],["Monthly estimate",money.format(avg*30*.145),(avg*30).toFixed(0)+" kWh"],["Temp correlation",corr.toFixed(2),"Pearson r"],["Unusual days",anomalies,"IQR method"]];
 $("#kpis").innerHTML=kpis.map(k=>`<article><span>${k[0]}</span><strong>${k[1]}</strong><small>${k[2]}</small></article>`).join("");$("#usage-chart").innerHTML=data.slice(-90).map(d=>`<i title="${d.date.toLocaleDateString()}: ${d.usage.toFixed(1)} kWh" style="height:${clamp(d.usage/Math.max(...usage)*100,3,100)}%"></i>`).join("");$("#distribution").innerHTML=[["Median",median.toFixed(1)+" kWh"],["Minimum",Math.min(...usage).toFixed(1)+" kWh"],["Maximum",Math.max(...usage).toFixed(1)+" kWh"],["Std. deviation",sd.toFixed(1)+" kWh"]].map(x=>`<span>${x[0]} <b>${x[1]}</b></span>`).join("");
 const hdd=data.reduce((s,d)=>s+Math.max(0,65-d.temp),0),cdd=data.reduce((s,d)=>s+Math.max(0,d.temp-65),0);$("#hdd").textContent=Math.round(hdd).toLocaleString();$("#cdd").textContent=`${Math.round(cdd).toLocaleString()} cooling degree days at a 65°F base.`;$("#energy-rows").innerHTML=data.slice(-100).reverse().map(d=>`<tr><td>${d.date.toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})}</td><td>${d.temp.toFixed(0)}° · ${d.temp<32?"Snow possible":d.temp>82?"Clear":"Partly cloudy"}</td><td><strong>${d.usage.toFixed(1)} kWh</strong></td><td>${money.format(d.cost)}</td><td>${money.format(d.rate)}</td></tr>`).join("");$("#records-title").textContent=`Recent ${cityName} records`;$("#analytics-provenance").textContent=`Two years of ${cityName} daily temperatures drive this synthetic household energy model.`;
}
function label(p){return[p.name,p.admin1,p.country].filter(Boolean).join(", ")}
async function searchCities(term){if(term.trim().length<2)return;const geo=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(term)}&count=8&language=en&format=json`).then(r=>r.json());suggestions=new Map((geo.results||[]).map(p=>[label(p),p]));$("#city-suggestions").innerHTML=[...suggestions.keys()].map(x=>`<option value="${x.replaceAll('"',"&quot;")}"></option>`).join("")}
$("#city").addEventListener("input",e=>{clearTimeout(suggestionTimer);suggestionTimer=setTimeout(()=>searchCities(e.target.value).catch(()=>{}),250)});
const weatherCode=c=>({0:"Clear skies",1:"Mainly clear",2:"Partly cloudy",3:"Overcast",45:"Fog",51:"Light drizzle",61:"Rain",71:"Snow",80:"Rain showers",95:"Thunderstorm"}[c]||"Current conditions");
async function loadHistorical(p){const end=new Date();end.setDate(end.getDate()-6);const start=new Date(end);start.setDate(start.getDate()-729);const iso=d=>d.toISOString().slice(0,10),url=`https://archive-api.open-meteo.com/v1/archive?latitude=${p.latitude}&longitude=${p.longitude}&start_date=${iso(start)}&end_date=${iso(end)}&daily=temperature_2m_mean&temperature_unit=fahrenheit&timezone=auto`,history=await fetch(url).then(r=>{if(!r.ok)throw Error("Historical weather is temporarily unavailable.");return r.json()});return history.daily.time.map((date,i)=>({date:new Date(date+"T12:00:00"),temp:history.daily.temperature_2m_mean[i]})).filter(x=>Number.isFinite(x.temp))}
$("#weather-form").addEventListener("submit",async e=>{e.preventDefault();const input=$("#city"),error=$("#weather-error"),status=$("#city-status"),button=e.submitter;error.hidden=true;button.disabled=true;button.textContent="Loading climate…";try{let p=suggestions.get(input.value);if(!p){await searchCities(input.value);p=suggestions.values().next().value}if(!p)throw Error("Location not found. Choose a city from the suggestions.");input.value=label(p);cityName=p.name;status.textContent=`Loading two years of ${p.name} weather and rebuilding energy analytics…`;const currentUrl=`https://api.open-meteo.com/v1/forecast?latitude=${p.latitude}&longitude=${p.longitude}&current=temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=auto`;const [w,temps]=await Promise.all([fetch(currentUrl).then(r=>r.json()),loadHistorical(p)]);if(temps.length<700)throw Error("Not enough historical weather was returned for this city.");data=buildEnergy(temps,p.latitude);render();$("#weather-place").textContent=label(p).toUpperCase();$("#weather-temp").textContent=`${Math.round(w.current.temperature_2m)}°`;$("#weather-description").textContent=weatherCode(w.current.weather_code);$("#weather-feels").textContent=`${Math.round(w.current.apparent_temperature)}°`;$("#weather-humidity").textContent=`${w.current.relative_humidity_2m}%`;$("#weather-wind").textContent=`${w.current.wind_speed_10m.toFixed(1)} mph`;$("#weather-highlow").textContent=`${Math.round(w.daily.temperature_2m_max[0])}° / ${Math.round(w.daily.temperature_2m_min[0])}°`;status.textContent=`Energy analytics now use ${temps.length} actual ${p.name} daily temperatures with demo household assumptions (1,850 sq ft, 3 occupants, heat pump, $0.145/kWh).`}catch(ex){error.textContent=ex.message;error.hidden=false;status.textContent="The previous city dataset is still active."}finally{button.disabled=false;button.textContent="Load city data →"}});
data=buildEnergy(temperatures());render();searchCities("Denver").catch(()=>{});
