const $=s=>document.querySelector(s),money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});
const STORAGE_KEY="wattweather.energy.v1",LOCATION_KEY="wattweather.location.v1";
let records=loadJson(STORAGE_KEY,[]),selectedLocation=loadJson(LOCATION_KEY,null),suggestions=new Map(),suggestionTimer,currentWeather=null,stateClimateCache=new Map();
function loadJson(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(records));if(selectedLocation)localStorage.setItem(LOCATION_KEY,JSON.stringify(selectedLocation))}
function label(p){return[p.name,p.admin1,p.country].filter(Boolean).join(", ")}
function localDate(value){const d=new Date(value+"T12:00:00");return Number.isNaN(d.valueOf())?null:d}
function weatherDescription(temp){return temp<32?"Snow possible":temp>82?"Warm / clear":"Mild / partly cloudy"}
function pearson(rows,x,y){if(rows.length<3)return null;const mx=rows.reduce((s,r)=>s+x(r),0)/rows.length,my=rows.reduce((s,r)=>s+y(r),0)/rows.length,num=rows.reduce((s,r)=>s+(x(r)-mx)*(y(r)-my),0),den=Math.sqrt(rows.reduce((s,r)=>s+(x(r)-mx)**2,0)*rows.reduce((s,r)=>s+(y(r)-my)**2,0));return den?num/den:null}
function regression(rows){const mx=rows.reduce((s,r)=>s+r.temp,0)/rows.length,my=rows.reduce((s,r)=>s+r.kwh,0)/rows.length,den=rows.reduce((s,r)=>s+(r.temp-mx)**2,0),slope=den?rows.reduce((s,r)=>s+(r.temp-mx)*(r.kwh-my),0)/den:0;return{slope,intercept:my-slope*mx,predict:t=>my+slope*(t-mx)}}
function renderPersonalAnalytics(matched,sorted){
 if(matched.length<3){$("#scatter-chart").innerHTML="";$("#scatter-caption").textContent="At least three weather-matched records are required";$("#temperature-bands").innerHTML="";$("#forecast-metrics").innerHTML="";return}
 const temps=matched.map(r=>r.temp),uses=matched.map(r=>r.kwh),minT=Math.min(...temps),maxT=Math.max(...temps),minU=Math.min(...uses),maxU=Math.max(...uses),scale=(v,min,max)=>max===min?50:5+(v-min)/(max-min)*90,model=regression(matched),corr=pearson(matched,r=>r.temp,r=>r.kwh);
 const points=matched.slice(-400).map(r=>`<circle cx="${scale(r.temp,minT,maxT)}" cy="${100-scale(r.kwh,minU,maxU)}" r="1.25"/>`).join(""),y1=100-scale(model.predict(minT),minU,maxU),y2=100-scale(model.predict(maxT),minU,maxU);$("#scatter-chart").innerHTML=`<svg viewBox="0 0 100 100" preserveAspectRatio="none"><g fill="#ff7657" opacity=".65">${points}</g><line x1="5" y1="${y1}" x2="95" y2="${y2}" stroke="#013e37" stroke-width=".8"/></svg>`;$("#scatter-caption").textContent=`${matched.length} records · Pearson r ${corr.toFixed(3)} · association does not prove causation`;
 const bands=[[-Infinity,32,"<32°F"],[32,50,"32–49°F"],[50,65,"50–64°F"],[65,80,"65–79°F"],[80,Infinity,"80°F+"]],summaries=bands.map(([lo,hi,label])=>{const rows=matched.filter(r=>r.temp>=lo&&r.temp<hi);return{label,count:rows.length,avg:rows.length?rows.reduce((s,r)=>s+r.kwh,0)/rows.length:0}}),bandMax=Math.max(1,...summaries.map(b=>b.avg));$("#temperature-bands").innerHTML=summaries.map(b=>`<div class="band-row"><span>${b.label}</span><div class="band-track"><i style="width:${b.avg/bandMax*100}%"></i></div><b>${b.count?b.avg.toFixed(1):"—"} kWh</b></div>`).join("");
 const span=(localDate(sorted.at(-1).date)-localDate(sorted[0].date))/864e5;if(matched.length<90||span<180){$("#forecast-metrics").innerHTML="";return}
 const split=Math.floor(matched.length*.8),train=matched.slice(0,split),test=matched.slice(split),forecast=regression(train),predictions=test.map(r=>({...r,predicted:forecast.predict(r.temp)})),mae=predictions.reduce((s,r)=>s+Math.abs(r.kwh-r.predicted),0)/predictions.length,rmse=Math.sqrt(predictions.reduce((s,r)=>s+(r.kwh-r.predicted)**2,0)/predictions.length),mean=test.reduce((s,r)=>s+r.kwh,0)/test.length,sse=predictions.reduce((s,r)=>s+(r.kwh-r.predicted)**2,0),sst=test.reduce((s,r)=>s+(r.kwh-mean)**2,0),r2=sst?1-sse/sst:0,next=currentWeather?forecast.predict(currentWeather.temperature_2m):null;$("#forecast-metrics").innerHTML=[["Forecast",next===null?"Select city":`${Math.max(0,next).toFixed(1)} kWh`,"at current temperature"],["MAE",`${mae.toFixed(2)} kWh`,"chronological test set"],["RMSE",`${rmse.toFixed(2)} kWh`,"chronological test set"],["R²",r2.toFixed(3),"temperature-only baseline"]].map(x=>`<article><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join("");
}
function render(){
 const sorted=[...records].sort((a,b)=>a.date.localeCompare(b.date)),usage=sorted.map(r=>r.kwh),has=sorted.length>0;
 $("#analytics-empty").hidden=has;$("#clear-records").hidden=!has;$("#records-title").textContent=has?`${sorted.length} real energy record${sorted.length===1?"":"s"}`:"Your energy records";
 if(!has){
  $("#hero-average").textContent="No records";$("#mini-bars").innerHTML="";["#stat-days","#stat-kwh","#stat-correlation","#stat-anomalies"].forEach(x=>$(x).textContent="—");
  $("#kpis").innerHTML="";$("#usage-chart").innerHTML="";$("#distribution").innerHTML="";$("#hdd").textContent="—";$("#cdd").textContent="Add weather-matched records to calculate degree days.";$("#energy-rows").innerHTML='<tr><td colspan="5">No records yet. Import a utility CSV or add one manually above.</td></tr>';renderPersonalAnalytics([],[]);return;
 }
 const total=usage.reduce((a,b)=>a+b,0),avg=total/usage.length,ordered=[...usage].sort((a,b)=>a-b),median=ordered.length%2?(ordered[(ordered.length-1)/2]):(ordered[ordered.length/2-1]+ordered[ordered.length/2])/2,sd=usage.length>1?Math.sqrt(usage.reduce((s,n)=>s+(n-avg)**2,0)/(usage.length-1)):0;
 const matched=sorted.filter(r=>Number.isFinite(r.temp)),meanT=matched.length?matched.reduce((s,r)=>s+r.temp,0)/matched.length:0,meanU=matched.length?matched.reduce((s,r)=>s+r.kwh,0)/matched.length:0,cov=matched.reduce((s,r)=>s+(r.temp-meanT)*(r.kwh-meanU),0),corrDen=Math.sqrt(matched.reduce((s,r)=>s+(r.temp-meanT)**2,0)*matched.reduce((s,r)=>s+(r.kwh-meanU)**2,0)),corr=corrDen?cov/corrDen:null;
 const q=p=>ordered[Math.floor((ordered.length-1)*p)],high=q(.75)+1.5*(q(.75)-q(.25)),anomalies=usage.filter(n=>n>high).length,totalCost=sorted.reduce((s,r)=>s+(r.cost||0),0),max=Math.max(...usage);
 $("#hero-average").textContent=`${avg.toFixed(1)} kWh`;$("#mini-bars").innerHTML=sorted.slice(-18).map(r=>`<i style="height:${Math.max(8,r.kwh/max*100)}%"></i>`).join("");$("#stat-days").textContent=sorted.length.toLocaleString();$("#stat-kwh").textContent=Math.round(total).toLocaleString();$("#stat-correlation").textContent=corr===null?"—":corr.toFixed(2);$("#stat-anomalies").textContent=anomalies;
 const kpis=[["Total usage",total.toFixed(1),"kWh"],["Daily average",avg.toFixed(1),"kWh / record"],["Total cost",totalCost?money.format(totalCost):"Not provided","from imported records"],["Weather matched",matched.length,`${sorted.length} total records`],["Temp correlation",corr===null?"Not enough data":corr.toFixed(2),"Pearson r"],["Unusual records",anomalies,"IQR method"]];
 $("#kpis").innerHTML=kpis.map(k=>`<article><span>${k[0]}</span><strong>${k[1]}</strong><small>${k[2]}</small></article>`).join("");$("#usage-chart").innerHTML=sorted.slice(-90).map(r=>`<i title="${r.date}: ${r.kwh.toFixed(2)} kWh" style="height:${Math.max(3,r.kwh/max*100)}%"></i>`).join("");$("#distribution").innerHTML=[["Median",median.toFixed(1)+" kWh"],["Minimum",Math.min(...usage).toFixed(1)+" kWh"],["Maximum",max.toFixed(1)+" kWh"],["Std. deviation",sd.toFixed(1)+" kWh"]].map(x=>`<span>${x[0]} <b>${x[1]}</b></span>`).join("");
 const hdd=matched.reduce((s,r)=>s+Math.max(0,65-r.temp),0),cdd=matched.reduce((s,r)=>s+Math.max(0,r.temp-65),0);$("#hdd").textContent=Math.round(hdd).toLocaleString();$("#cdd").textContent=`${Math.round(cdd).toLocaleString()} cooling degree days across weather-matched records.`;$("#energy-rows").innerHTML=sorted.slice(-100).reverse().map(r=>`<tr><td>${localDate(r.date).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})}</td><td>${Number.isFinite(r.temp)?`${r.temp.toFixed(0)}° · ${weatherDescription(r.temp)}`:"Weather unavailable"}</td><td><strong>${r.kwh.toFixed(2)} kWh</strong></td><td>${r.cost==null?"—":money.format(r.cost)}</td><td>${r.cost&&r.kwh?money.format(r.cost/r.kwh):"—"}</td></tr>`).join("");
 const span=(localDate(sorted.at(-1).date)-localDate(sorted[0].date))/864e5;$("#forecast-status").textContent=sorted.length>=90&&span>=180?`Ready for model training with ${sorted.length} real observations spanning ${Math.round(span)} days. Predictions remain estimates.`:`Add ${Math.max(0,90-sorted.length)} more observations and cover at least six months before an estimate is shown.`;
 $("#analytics-provenance").textContent=`Analytics use ${sorted.length} user-provided energy records; ${matched.length} are matched to ${selectedLocation?.name||"selected-city"} weather.`;
 renderPersonalAnalytics(matched,sorted);
}
function showSuggestions(){
 const menu=$("#city-suggestions"),items=[...suggestions.entries()];menu.innerHTML=items.map(([name,p],i)=>`<button type="button" data-city-index="${i}"><b>${p.name}</b><span>${[p.admin1,p.country].filter(Boolean).join(", ")}</span></button>`).join("");menu.hidden=!items.length;
}
async function searchCities(term){if(term.trim().length<2){suggestions.clear();showSuggestions();return}const geo=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(term)}&count=8&language=en&format=json`).then(r=>r.json());suggestions=new Map((geo.results||[]).map(p=>[label(p),p]));showSuggestions()}
$("#city").addEventListener("input",e=>{clearTimeout(suggestionTimer);suggestionTimer=setTimeout(()=>searchCities(e.target.value).catch(()=>{}),220)});
$("#city").addEventListener("focus",e=>{if(e.target.value.trim().length>=2)searchCities(e.target.value).catch(()=>{})});
$("#city").addEventListener("keydown",e=>{const menu=$("#city-suggestions"),buttons=[...menu.querySelectorAll("button")];if(!buttons.length)return;let active=buttons.findIndex(b=>b.classList.contains("active"));if(e.key==="ArrowDown"){e.preventDefault();active=(active+1)%buttons.length}else if(e.key==="ArrowUp"){e.preventDefault();active=(active-1+buttons.length)%buttons.length}else if(e.key==="Enter"&&active>=0){e.preventDefault();buttons[active].click();return}else if(e.key==="Escape"){menu.hidden=true;return}else{return}buttons.forEach((b,i)=>b.classList.toggle("active",i===active));buttons[active].scrollIntoView({block:"nearest"})});
$("#city-suggestions").addEventListener("mousedown",e=>{const button=e.target.closest("button");if(!button)return;e.preventDefault();const entry=[...suggestions.entries()][Number(button.dataset.cityIndex)];$("#city").value=entry[0];$("#city").dataset.selected=entry[0];$("#city-suggestions").hidden=true});
document.addEventListener("click",e=>{if(!e.target.closest(".city-picker"))$("#city-suggestions").hidden=true});
const weatherCode=c=>({0:"Clear skies",1:"Mainly clear",2:"Partly cloudy",3:"Overcast",45:"Fog",51:"Light drizzle",61:"Rain",71:"Snow",80:"Rain showers",95:"Thunderstorm"}[c]||"Current conditions");
async function renderEia(stateName){
 $("#eia-rate").textContent="Loading…";$("#eia-usage").textContent="Loading…";
 try{const response=await fetch(`data/eia-state-energy.json?v=${Date.now()}`);if(!response.ok)throw Error();const states=await response.json(),row=states.states?.[stateName];if(!row)throw Error();$("#eia-rate").textContent=`${Number(row.residentialPriceCents).toFixed(2)}¢/kWh`;$("#eia-usage").textContent=`${Math.round(row.averageMonthlyKwh).toLocaleString()} kWh/mo`;$("#eia-rate-note").textContent=`${stateName} residential average · EIA ${row.period}`;$("#eia-usage-note").textContent=`State residential sales ÷ customers · EIA ${row.period}`;await renderStateCorrelation(row,stateName)}
 catch{$("#eia-rate").textContent="Unavailable";$("#eia-usage").textContent="Unavailable";$("#eia-rate-note").textContent="Run the secure EIA update workflow";$("#eia-usage-note").textContent="No API key is exposed to this browser";$("#state-correlation").textContent="—";$("#state-correlation-note").textContent="State analysis is currently unavailable"}
}
async function renderStateCorrelation(state,stateName){
 const history=state.history||[];if(history.length<4||!selectedLocation){$("#state-correlation").textContent="—";$("#state-correlation-note").textContent="At least four annual EIA observations are required";return}
 $("#state-correlation").textContent="…";$("#state-correlation-note").textContent="Matching annual EIA usage with city temperature history";
 const key=`${selectedLocation.latitude.toFixed(2)},${selectedLocation.longitude.toFixed(2)},${history[0].period},${history.at(-1).period}`;let annual=stateClimateCache.get(key);
 if(!annual){const start=`${history[0].period}-01-01`,end=`${history.at(-1).period}-12-31`,url=`https://archive-api.open-meteo.com/v1/archive?latitude=${selectedLocation.latitude}&longitude=${selectedLocation.longitude}&start_date=${start}&end_date=${end}&daily=temperature_2m_mean&temperature_unit=fahrenheit&timezone=auto`,weather=await fetch(url).then(r=>{if(!r.ok)throw Error("Annual weather unavailable");return r.json()});const groups={};weather.daily.time.forEach((date,i)=>{const year=date.slice(0,4),temp=weather.daily.temperature_2m_mean[i];if(Number.isFinite(temp))(groups[year]??=[]).push(temp)});annual=Object.fromEntries(Object.entries(groups).map(([year,values])=>[year,values.reduce((a,b)=>a+b,0)/values.length]));stateClimateCache.set(key,annual)}
 const joined=history.filter(x=>Number.isFinite(annual[x.period])).map(x=>({temp:annual[x.period],kwh:x.averageMonthlyKwh})),r=pearson(joined,x=>x.temp,x=>x.kwh);$("#state-correlation").textContent=r===null?"—":r.toFixed(3);$("#state-correlation-note").textContent=r===null?"Not enough matched years":`${joined.length} annual observations · ${selectedLocation.city} temperature is a climate proxy for ${stateName}; correlation is not causation`;
}
async function selectCity(inputValue){
 let p=suggestions.get(inputValue);if(!p){await searchCities(inputValue);p=suggestions.values().next().value}if(!p)throw Error("Location not found. Choose a city from the suggestions.");
 const url=`https://api.open-meteo.com/v1/forecast?latitude=${p.latitude}&longitude=${p.longitude}&current=temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,shortwave_radiation_sum&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=auto`,w=await fetch(url).then(r=>r.json());
 selectedLocation={name:label(p),city:p.name,state:p.admin1||null,countryCode:p.country_code||null,latitude:p.latitude,longitude:p.longitude};currentWeather=w.current;save();$("#city").value=selectedLocation.name;$("#weather-place").textContent=selectedLocation.name.toUpperCase();$("#weather-temp").textContent=`${Math.round(w.current.temperature_2m)}°`;$("#weather-description").textContent=weatherCode(w.current.weather_code);$("#weather-feels").textContent=`${Math.round(w.current.apparent_temperature)}°`;$("#weather-humidity").textContent=`${w.current.relative_humidity_2m}%`;$("#weather-wind").textContent=`${w.current.wind_speed_10m.toFixed(1)} mph`;$("#weather-highlow").textContent=`${Math.round(w.daily.temperature_2m_max[0])}° / ${Math.round(w.daily.temperature_2m_min[0])}°`;$("#hero-city").textContent=p.name.toUpperCase();$("#hero-temp").textContent=`${Math.round(w.current.temperature_2m)}°`;$("#hero-condition").textContent=weatherCode(w.current.weather_code);
 const solar=w.daily.shortwave_radiation_sum,solarToday=solar[0]/3.6,solarWeek=solar.reduce((a,b)=>a+b,0)/3.6,average=(w.daily.temperature_2m_max[0]+w.daily.temperature_2m_min[0])/2,load=average<55?"Heating demand likely":average>75?"Cooling demand likely":"Mild demand outlook";$("#solar-potential").textContent=`${solarToday.toFixed(1)} kWh/m²`;$("#solar-week").textContent=`${solarWeek.toFixed(1)} kWh/m²`;$("#climate-load").textContent=load;$("#city-energy").hidden=false;await renderEia(selectedLocation.state);$("#city-status").textContent=`Selected ${selectedLocation.name}. New energy records will be matched to this location's weather and EIA state statistics.`;return p;
}
$("#weather-form").addEventListener("submit",async e=>{e.preventDefault();const button=e.submitter,error=$("#weather-error");button.disabled=true;error.hidden=true;try{await selectCity($("#city").value);await enrichRecords();render()}catch(ex){error.textContent=ex.message;error.hidden=false}finally{button.disabled=false;button.textContent="Load city data →"}});
async function weatherMapForDates(dates){
 if(!selectedLocation)throw Error("Select the energy-use city in the Weather section first.");const unique=[...new Set(dates)].sort(),cutoff=new Date();cutoff.setDate(cutoff.getDate()-6);const cutoffIso=cutoff.toISOString().slice(0,10),historical=unique.filter(d=>d<=cutoffIso),map=new Map();
 if(historical.length){const start=historical[0],end=historical.at(-1),url=`https://archive-api.open-meteo.com/v1/archive?latitude=${selectedLocation.latitude}&longitude=${selectedLocation.longitude}&start_date=${start}&end_date=${end}&daily=temperature_2m_mean&temperature_unit=fahrenheit&timezone=auto`,h=await fetch(url).then(r=>{if(!r.ok)throw Error("Historical weather is temporarily unavailable.");return r.json()});h.daily.time.forEach((d,i)=>map.set(d,h.daily.temperature_2m_mean[i]))}
 unique.filter(d=>d>cutoffIso).forEach(d=>{if(currentWeather)map.set(d,currentWeather.temperature_2m)});return map;
}
async function enrichRecords(){if(!records.length||!selectedLocation)return;const map=await weatherMapForDates(records.filter(r=>!Number.isFinite(r.temp)||r.location!==selectedLocation.name).map(r=>r.date));records=records.map(r=>map.has(r.date)?{...r,temp:map.get(r.date),location:selectedLocation.name}:r);save()}
function parseCsv(text){
 const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean),split=line=>line.match(/(?:\"([^\"]*(?:\"\"[^\"]*)*)\"|([^,]*))(?:,|$)/g)?.map(x=>x.replace(/,$/,"").replace(/^\"|\"$/g,"").replaceAll('""','"').trim())||[];
 if(lines.length<2)throw Error("The CSV has no data rows.");const headers=split(lines[0]).map(h=>h.toLowerCase().replace(/[^a-z0-9]/g,"")),find=names=>headers.findIndex(h=>names.includes(h)),dateIndex=find(["date","usagedate","startdate","billingdate"]),kwhIndex=find(["kwh","usage","energykwh","electricityusagekwh"]),costIndex=find(["cost","totalcost","amount","electricitycost"]);if(dateIndex<0||kwhIndex<0)throw Error("CSV columns must include date and kwh.");
 return lines.slice(1).map((line,i)=>{const c=split(line),date=localDate(c[dateIndex]),kwh=Number(c[kwhIndex]),cost=costIndex>=0&&c[costIndex]!==""?Number(c[costIndex]):null;if(!date||!Number.isFinite(kwh)||kwh<=0)throw Error(`Invalid date or kWh on CSV row ${i+2}.`);if(cost!==null&&(!Number.isFinite(cost)||cost<0))throw Error(`Invalid cost on CSV row ${i+2}.`);return{date:c[dateIndex].slice(0,10),kwh,cost,source:"CSV"}})
}
async function addRecords(incoming){if(!selectedLocation)throw Error("Select the energy-use city in the Weather section first.");const map=await weatherMapForDates(incoming.map(r=>r.date)),byDate=new Map(records.map(r=>[r.date,r]));incoming.forEach(r=>byDate.set(r.date,{...r,temp:map.get(r.date)??null,location:selectedLocation.name}));records=[...byDate.values()];save();render()}
$("#csv-file").addEventListener("change",async e=>{const message=$("#data-message");try{const incoming=parseCsv(await e.target.files[0].text());message.textContent=`Matching ${incoming.length} imported records to ${selectedLocation?.name||"weather"}…`;await addRecords(incoming);message.textContent=`Imported ${incoming.length} real energy records and matched available historical weather. Records remain in this browser.`}catch(ex){message.textContent=ex.message}finally{e.target.value=""}});
$("#record-date").value=new Date().toISOString().slice(0,10);$("#record-form").addEventListener("submit",async e=>{e.preventDefault();const kwh=Number($("#record-kwh").value),cost=$("#record-cost").value===""?null:Number($("#record-cost").value),message=$("#data-message");try{await addRecords([{date:$("#record-date").value,kwh,cost,source:"Manual"}]);message.textContent="Saved the real energy record and matched available weather.";e.target.reset();$("#record-date").value=new Date().toISOString().slice(0,10)}catch(ex){message.textContent=ex.message}});
$("#clear-records").addEventListener("click",()=>{if(confirm("Remove all energy records stored in this browser?")){records=[];save();render();$("#data-message").textContent="All local energy records were removed."}});
if(selectedLocation){$("#city").value=selectedLocation.name;$("#hero-city").textContent=selectedLocation.name.split(",")[0].toUpperCase()}render();searchCities(selectedLocation?.name||"Denver").catch(()=>{});
