services:
  - type: web
    name: wattweather
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeployTrigger: checksPass
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
