name: Build MAUI Windows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install MAUI workload
        run: dotnet workload install maui-windows

      - name: Restore
        run: dotnet restore .\OpenWeather\OpenWeather.csproj -r win-x64 -p:PublishReadyToRun=false

      - name: Build (Windows target)
        run: dotnet build .\OpenWeather\OpenWeather.csproj -c Release -f net10.0-windows10.0.19041.0 -r win-x64 --no-restore -p:PublishReadyToRun=false
